name: Rector

on:
  workflow_call:
    inputs:
      PHP_VERSION:
        required: true
        type: string
      PHP_EXTENSIONS:
        required: true
        type: string
      PHP_INI_PROPERTIES:
        required: true
        type: string
      COMPOSER_FLAGS:
        required: true
        type: string
      CACHE_KEY:
        required: true
        type: string

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-rector
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup PHP
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          extensions: ${{ inputs.PHP_EXTENSIONS }}
          ini-values: ${{ inputs.PHP_INI_PROPERTIES }}
          coverage: xdebug
          tools: composer:v2

      - name: Install composer dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3.1.1
        with:
          composer-options: ${{ inputs.COMPOSER_FLAGS }}
          custom-cache-key: ${{ inputs.CACHE_KEY }}

      - name: Run Rector
        run: |
          vendor/bin/rector --dry-run --output-format=github
